// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhmPYRezi75zm8LGQV4fa7DAdj4uxOp8o',
    appId: '1:860561882322:web:31930cfddefb4cb6e2c10b',
    messagingSenderId: '860561882322',
    projectId: 'atmetha',
    authDomain: 'atmetha.firebaseapp.com',
    storageBucket: 'atmetha.appspot.com',
    measurementId: 'G-LQ48RS79WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT2XBDxALn_452yZpi7ky6YM56HYpC1cA',
    appId: '1:860561882322:android:362312520f77c9fce2c10b',
    messagingSenderId: '860561882322',
    projectId: 'atmetha',
    storageBucket: 'atmetha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXKepVTv-KskMsdYM0p-Pi1fNmMJdHwNM',
    appId: '1:860561882322:ios:041fd1d3ae719421e2c10b',
    messagingSenderId: '860561882322',
    projectId: 'atmetha',
    storageBucket: 'atmetha.appspot.com',
    iosBundleId: 'com.example.findYourTeacher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXKepVTv-KskMsdYM0p-Pi1fNmMJdHwNM',
    appId: '1:860561882322:ios:041fd1d3ae719421e2c10b',
    messagingSenderId: '860561882322',
    projectId: 'atmetha',
    storageBucket: 'atmetha.appspot.com',
    iosBundleId: 'com.example.findYourTeacher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhmPYRezi75zm8LGQV4fa7DAdj4uxOp8o',
    appId: '1:860561882322:web:b6ed1942426f3229e2c10b',
    messagingSenderId: '860561882322',
    projectId: 'atmetha',
    authDomain: 'atmetha.firebaseapp.com',
    storageBucket: 'atmetha.appspot.com',
    measurementId: 'G-SK5JXM129S',
  );

}